version: '3'

services:
    db:
        build:
            dockerfile: db.Dockerfile
        restart: always
        env_file: .env
        ports:
            - '5432:5432'
        volumes:
            - db-data:/var/lib/postgresql/data
        networks:
            - app-network
    app:
        build:
            dockerfile: app.Dockerfile
        ports:
            - '0.0.0.0:8000:5000'
        env_file: .env
        links:
            - db:dbserver
        restart: always
        depends_on:
            - db
        networks:
            - app-network
networks:
    app-network:
        driver: bridge
volumes:
    db-data:
