"""empty message

Revision ID: 597d812293ac
Revises: f27631c6d583
Create Date: 2023-09-15 11:33:10.214015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '597d812293ac'
down_revision = 'f27631c6d583'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
